image: hiimivantang/workspace-yugabytedb

tasks:
  - name: ysqlsh
    before: |
      git clone https://github.com/hiimivantang/yb-docker-composer 
      cd yb-docker-composer 
      python yb-docker-composer.py
    init: docker-compose pull
    command: |
      docker-compose up -d
      sleep 5
      ysqlsh

  - name: psql
    before: brew install libpq && brew link --force libpq
    command: |
      docker run --name postgresql -e POSTGRES_USER=postgres -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 -v ~/postgresql_data/:/var/lib/postgresql/data -d postgres
      sleept 5
      psql postgresql://postgres:postgres@localhost


ports:
  - port: 7001
    onOpen: open-browser
    description: "UI for yb-master-n1"
  - port: 7002
    onOpen: ignore
    description: "UI for yb-master-n2"
  - port: 7003
    onOpen: ignore
    description: "UI for yb-master-n3"
  - port: 9090
    onOpen: ignore
    description: "Prometheus"
  - port: 3000
    onOpen: open-browser
    description: "Grafana dashboard"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
